import type { GetServerSideProps, InferGetServerSidePropsType } from "next";
import Head from "next/head";
import Card from "../components/Card";
import styles from "../styles/Home.module.css";

import { Resource } from "../model/Resource";
import { prisma } from "../prisma/db";

export const getServerSideProps: GetServerSideProps = async (context) => {
  let resources: Resource[] = await prisma.resources.findMany();
  resources = resources.map((resource) => {
    // resource.dateCreated = Math.floor(resource.dateCreated / 1000);
    resource.dateCreated = null;
    return resource;
  });
  return { props: { resources: [...resources] } };
};

export function Home(
  props: InferGetServerSidePropsType<typeof getServerSideProps>
) {
  const resources = props.resources;

  return (
    <div className={styles.container}>
      <Head>
        <title>Home</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <main className={styles.main}>
        {resources.map(({ id, displayName, link }: Resource) => (
          <Card key={id} id={id} displayName={displayName} link={link} />
        ))}
      </main>
      <footer className={styles.footer}></footer>
    </div>
  );
}

export default Home;
